/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Customer Login Colors
        "clogin-on-tertiary": "#5e5f5f",
        "clogin-primary-fixed-dim": "#d4d4d4",
        "clogin-surface-container-high": "#1f2020",
        "clogin-surface-container-lowest": "#000000",
        "clogin-error-dim": "#bb5551",
        "clogin-primary-dim": "#b9b9b9",
        "clogin-surface-container-low": "#131313",
        "clogin-tertiary-fixed": "#f4f3f3",
        "clogin-secondary-container": "#3b3b3b",
        "clogin-on-surface-variant": "#acabaa",
        "clogin-on-secondary-fixed": "#3f3f3f",
        "clogin-tertiary-dim": "#ebebeb",
        "clogin-surface": "#0e0e0e",
        "clogin-inverse-surface": "#fcf9f8",
        "clogin-primary-container": "#464747",
        "clogin-surface-bright": "#2c2c2c",
        "clogin-background": "#0e0e0e",
        "clogin-on-primary-fixed-variant": "#5a5c5c",
        "clogin-surface-dim": "#0e0e0e",
        "clogin-error": "#ee7d77",
        "clogin-on-surface": "#e7e5e4",
        "clogin-surface-tint": "#c6c6c6",
        "clogin-surface-variant": "#252626",
        "clogin-on-secondary": "#202020",
        "clogin-on-error-container": "#ff9993",
        "clogin-secondary": "#9f9d9d",
        "clogin-on-tertiary-container": "#555757",
        "clogin-on-primary-container": "#d0d0d0",
        "clogin-secondary-fixed": "#e4e2e2",
        "clogin-primary": "#c6c6c6",
        "clogin-primary-fixed": "#e3e2e2",
        "clogin-secondary-fixed-dim": "#d6d4d4",
        "clogin-on-secondary-fixed-variant": "#5c5b5b",
        "clogin-error-container": "#7f2927",
        "clogin-tertiary": "#f9f9f9",
        "clogin-on-primary": "#3f4041",
        "clogin-on-tertiary-fixed-variant": "#656667",
        "clogin-surface-container": "#191a1a",
        "clogin-on-tertiary-fixed": "#484a4a",
        "clogin-on-error": "#490106",
        "clogin-tertiary-fixed-dim": "#e5e5e5",
        "clogin-on-background": "#e7e5e4",
        "clogin-secondary-dim": "#9f9d9d",
        "clogin-inverse-on-surface": "#565555",
        "clogin-inverse-primary": "#5e5f5f",
        "clogin-outline-variant": "#484848",
        "clogin-surface-container-highest": "#252626",
        "clogin-on-secondary-container": "#c0bfbe",
        "clogin-tertiary-container": "#ebebeb",
        "clogin-outline": "#767575",
        "clogin-on-primary-fixed": "#3e3f40",
        // Employee Module Colors
        "edash-tertiary-dim": "#005980",
        "edash-tertiary-container": "#34b5fa",
        "edash-surface-container": "#e8eff3",
        "edash-primary-dim": "#485367",
        "edash-inverse-surface": "#0b0f10",
        "edash-outline": "#717c82",
        "edash-primary-fixed": "#d8e3fb",
        "edash-surface-container-high": "#e1e9ee",
        "edash-surface-dim": "#cfdce3",
        "edash-primary-fixed-dim": "#cad5ed",
        "edash-primary": "#545f73",
        "edash-on-secondary": "#f7f9ff",
        "edash-surface-container-highest": "#d9e4ea",
        "edash-inverse-primary": "#dae6fe",
        "edash-surface-bright": "#f7f9fb",
        "edash-on-primary-fixed-variant": "#515c70",
        "edash-primary-container": "#d8e3fb",
        "edash-on-tertiary": "#f5f9ff",
        "edash-on-secondary-fixed-variant": "#4d5d73",
        "edash-outline-variant": "#a9b4b9",
        "edash-surface": "#f7f9fb",
        "edash-on-error": "#fff7f6",
        "edash-tertiary-fixed-dim": "#17a8ec",
        "edash-on-primary-fixed": "#354053",
        "edash-error-container": "#fe8983",
        "edash-surface-container-lowest": "#ffffff",
        "edash-surface-tint": "#545f73",
        "edash-on-tertiary-fixed-variant": "#003954",
        "edash-error": "#9f403d",
        "edash-secondary-dim": "#44546a",
        "edash-tertiary-fixed": "#34b5fa",
        "edash-on-surface": "#2a3439",
        "edash-inverse-on-surface": "#9a9d9f",
        "edash-secondary": "#506076",
        "edash-on-tertiary-container": "#003047",
        "edash-on-surface-variant": "#566166",
        "edash-on-error-container": "#752121",
        "edash-background": "#f7f9fb",
        "edash-tertiary": "#006592",
        "edash-on-tertiary-fixed": "#00121e",
        "edash-surface-variant": "#d9e4ea",
        "edash-secondary-fixed-dim": "#c5d6f0",
        "edash-on-background": "#2a3439",
        "edash-error-dim": "#4e0309",
        "edash-surface-container-low": "#f0f4f7",
        "edash-on-secondary-fixed": "#314055",
        "edash-on-primary-container": "#475266",
        "edash-on-primary": "#f6f7ff",
        "edash-secondary-container": "#d3e4fe",
        "edash-on-secondary-container": "#435368",
        "edash-secondary-fixed": "#d3e4fe",
        "einq-tertiary-dim": "#005980",
        "einq-tertiary-container": "#34b5fa",
        "einq-surface-container": "#e8eff3",
        "einq-primary-dim": "#485367",
        "einq-inverse-surface": "#0b0f10",
        "einq-outline": "#717c82",
        "einq-primary-fixed": "#d8e3fb",
        "einq-surface-container-high": "#e1e9ee",
        "einq-surface-dim": "#cfdce3",
        "einq-primary-fixed-dim": "#cad5ed",
        "einq-primary": "#545f73",
        "einq-on-secondary": "#f7f9ff",
        "einq-surface-container-highest": "#d9e4ea",
        "einq-inverse-primary": "#dae6fe",
        "einq-surface-bright": "#f7f9fb",
        "einq-on-primary-fixed-variant": "#515c70",
        "einq-primary-container": "#d8e3fb",
        "einq-on-tertiary": "#f5f9ff",
        "einq-on-secondary-fixed-variant": "#4d5d73",
        "einq-outline-variant": "#a9b4b9",
        "einq-surface": "#f7f9fb",
        "einq-on-error": "#fff7f6",
        "einq-tertiary-fixed-dim": "#17a8ec",
        "einq-on-primary-fixed": "#354053",
        "einq-error-container": "#fe8983",
        "einq-surface-container-lowest": "#ffffff",
        "einq-surface-tint": "#545f73",
        "einq-on-tertiary-fixed-variant": "#003954",
        "einq-error": "#9f403d",
        "einq-secondary-dim": "#44546a",
        "einq-tertiary-fixed": "#34b5fa",
        "einq-on-surface": "#2a3439",
        "einq-inverse-on-surface": "#9a9d9f",
        "einq-secondary": "#506076",
        "einq-on-tertiary-container": "#003047",
        "einq-on-surface-variant": "#566166",
        "einq-on-error-container": "#752121",
        "einq-background": "#f7f9fb",
        "einq-tertiary": "#006592",
        "einq-on-tertiary-fixed": "#00121e",
        "einq-surface-variant": "#d9e4ea",
        "einq-secondary-fixed-dim": "#c5d6f0",
        "einq-on-background": "#2a3439",
        "einq-error-dim": "#4e0309",
        "einq-surface-container-low": "#f0f4f7",
        "einq-on-secondary-fixed": "#314055",
        "einq-on-primary-container": "#475266",
        "einq-on-primary": "#f6f7ff",
        "einq-secondary-container": "#d3e4fe",
        "einq-on-secondary-container": "#435368",
        "einq-secondary-fixed": "#d3e4fe",
        "eassign-tertiary-dim": "#005980",
        "eassign-tertiary-container": "#34b5fa",
        "eassign-surface-container": "#e8eff3",
        "eassign-primary-dim": "#485367",
        "eassign-inverse-surface": "#0b0f10",
        "eassign-outline": "#717c82",
        "eassign-primary-fixed": "#d8e3fb",
        "eassign-surface-container-high": "#e1e9ee",
        "eassign-surface-dim": "#cfdce3",
        "eassign-primary-fixed-dim": "#cad5ed",
        "eassign-primary": "#545f73",
        "eassign-on-secondary": "#f7f9ff",
        "eassign-surface-container-highest": "#d9e4ea",
        "eassign-inverse-primary": "#dae6fe",
        "eassign-surface-bright": "#f7f9fb",
        "eassign-on-primary-fixed-variant": "#515c70",
        "eassign-primary-container": "#d8e3fb",
        "eassign-on-tertiary": "#f5f9ff",
        "eassign-on-secondary-fixed-variant": "#4d5d73",
        "eassign-outline-variant": "#a9b4b9",
        "eassign-surface": "#f7f9fb",
        "eassign-on-error": "#fff7f6",
        "eassign-tertiary-fixed-dim": "#17a8ec",
        "eassign-on-primary-fixed": "#354053",
        "eassign-error-container": "#fe8983",
        "eassign-surface-container-lowest": "#ffffff",
        "eassign-surface-tint": "#545f73",
        "eassign-on-tertiary-fixed-variant": "#003954",
        "eassign-error": "#9f403d",
        "eassign-secondary-dim": "#44546a",
        "eassign-tertiary-fixed": "#34b5fa",
        "eassign-on-surface": "#2a3439",
        "eassign-inverse-on-surface": "#9a9d9f",
        "eassign-secondary": "#506076",
        "eassign-on-tertiary-container": "#003047",
        "eassign-on-surface-variant": "#566166",
        "eassign-on-error-container": "#752121",
        "eassign-background": "#f7f9fb",
        "eassign-tertiary": "#006592",
        "eassign-on-tertiary-fixed": "#00121e",
        "eassign-surface-variant": "#d9e4ea",
        "eassign-secondary-fixed-dim": "#c5d6f0",
        "eassign-on-background": "#2a3439",
        "eassign-error-dim": "#4e0309",
        "eassign-surface-container-low": "#f0f4f7",
        "eassign-on-secondary-fixed": "#314055",
        "eassign-on-primary-container": "#475266",
        "eassign-on-primary": "#f6f7ff",
        "eassign-secondary-container": "#d3e4fe",
        "eassign-on-secondary-container": "#435368",
        "eassign-secondary-fixed": "#d3e4fe",
        "eperf-tertiary-dim": "#005980",
        "eperf-tertiary-container": "#34b5fa",
        "eperf-surface-container": "#e8eff3",
        "eperf-primary-dim": "#485367",
        "eperf-inverse-surface": "#0b0f10",
        "eperf-outline": "#717c82",
        "eperf-primary-fixed": "#d8e3fb",
        "eperf-surface-container-high": "#e1e9ee",
        "eperf-surface-dim": "#cfdce3",
        "eperf-primary-fixed-dim": "#cad5ed",
        "eperf-primary": "#545f73",
        "eperf-on-secondary": "#f7f9ff",
        "eperf-surface-container-highest": "#d9e4ea",
        "eperf-inverse-primary": "#dae6fe",
        "eperf-surface-bright": "#f7f9fb",
        "eperf-on-primary-fixed-variant": "#515c70",
        "eperf-primary-container": "#d8e3fb",
        "eperf-on-tertiary": "#f5f9ff",
        "eperf-on-secondary-fixed-variant": "#4d5d73",
        "eperf-outline-variant": "#a9b4b9",
        "eperf-surface": "#f7f9fb",
        "eperf-on-error": "#fff7f6",
        "eperf-tertiary-fixed-dim": "#17a8ec",
        "eperf-on-primary-fixed": "#354053",
        "eperf-error-container": "#fe8983",
        "eperf-surface-container-lowest": "#ffffff",
        "eperf-surface-tint": "#545f73",
        "eperf-on-tertiary-fixed-variant": "#003954",
        "eperf-error": "#9f403d",
        "eperf-secondary-dim": "#44546a",
        "eperf-tertiary-fixed": "#34b5fa",
        "eperf-on-surface": "#2a3439",
        "eperf-inverse-on-surface": "#9a9d9f",
        "eperf-secondary": "#506076",
        "eperf-on-tertiary-container": "#003047",
        "eperf-on-surface-variant": "#566166",
        "eperf-on-error-container": "#752121",
        "eperf-background": "#f7f9fb",
        "eperf-tertiary": "#006592",
        "eperf-on-tertiary-fixed": "#00121e",
        "eperf-surface-variant": "#d9e4ea",
        "eperf-secondary-fixed-dim": "#c5d6f0",
        "eperf-on-background": "#2a3439",
        "eperf-error-dim": "#4e0309",
        "eperf-surface-container-low": "#f0f4f7",
        "eperf-on-secondary-fixed": "#314055",
        "eperf-on-primary-container": "#475266",
        "eperf-on-primary": "#f6f7ff",
        "eperf-secondary-container": "#d3e4fe",
        "eperf-on-secondary-container": "#435368",
        "eperf-secondary-fixed": "#d3e4fe",
        "serene-primary": "#1a2a44",
        "serene-bg-light": "#f8f6f6",
        "serene-bg-dark": "#221610",
        "serene-blue": "#e0f2f1",
        "serene-peach": "#fdf2f0",
        "serene-green": "#f1f8e9",
        "serene-matte": "#1A1A1A",
        "serene-silver": "#E5E7EB",
        "serene-brushed": "#C0C0C0",
        "serene-accent": "#F3F4F6",

        "dealer-tertiary-container": "#34b5fa",
        "dealer-on-surface": "#2a3439",
        "dealer-tertiary-fixed-dim": "#17a8ec",
        "dealer-on-tertiary": "#f5f9ff",
        "dealer-outline": "#717c82",
        "dealer-on-tertiary-fixed-variant": "#003954",
        "dealer-primary": "#545f73",
        "dealer-on-primary-fixed-variant": "#515c70",
        "dealer-on-error": "#fff7f6",
        "dealer-secondary-fixed": "#d3e4fe",
        "dealer-secondary-fixed-dim": "#c5d6f0",
        "dealer-error": "#9f403d",
        "dealer-on-secondary-fixed": "#314055",
        "dealer-surface-container-low": "#f0f4f7",
        "dealer-surface-tint": "#545f73",
        "dealer-surface-variant": "#d9e4ea",
        "dealer-surface-container-lowest": "#ffffff",
        "dealer-on-tertiary-fixed": "#00121e",
        "dealer-primary-fixed-dim": "#cad5ed",
        "dealer-inverse-primary": "#dae6fe",
        "dealer-surface-bright": "#f7f9fb",
        "dealer-tertiary-dim": "#005980",
        "dealer-surface-dim": "#cfdce3",
        "dealer-on-secondary": "#f7f9ff",
        "dealer-surface-container": "#e8eff3",
        "dealer-tertiary": "#006592",
        "dealer-on-background": "#2a3439",
        "dealer-primary-dim": "#485367",
        "dealer-surface-container-highest": "#d9e4ea",
        "dealer-on-error-container": "#752121",
        "dealer-on-secondary-fixed-variant": "#4d5d73",
        "dealer-secondary": "#506076",
        "dealer-primary-container": "#d8e3fb",
        "dealer-outline-variant": "#a9b4b9",
        "dealer-on-surface-variant": "#566166",
        "dealer-surface": "#f7f9fb",
        "dealer-primary-fixed": "#d8e3fb",
        "dealer-inverse-surface": "#0b0f10",
        "dealer-on-primary-fixed": "#354053",
        "dealer-secondary-container": "#d3e4fe",
        "dealer-on-primary-container": "#475266",
        "dealer-on-secondary-container": "#435368",
        "dealer-background": "#f7f9fb",
        "dealer-on-primary": "#f6f7ff",
        "dealer-on-tertiary-container": "#003047",
        "dealer-tertiary-fixed": "#34b5fa",
        "dealer-error-container": "#fe8983",
        "dealer-secondary-dim": "#44546a",
        "dealer-surface-container-high": "#e1e9ee",
        "dealer-inverse-on-surface": "#9a9d9f",
        "dealer-error-dim": "#4e0309"
      },
      fontFamily: {
        display: ['Public Sans', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      "fade-in-up": {
        from: { opacity: "0", transform: "translateY(30px)" },
        to: { opacity: "1", transform: "translateY(0)" },
      },
      "bounce-slow": {
        "0%, 100%": { transform: "translateY(0)" },
        "50%": { transform: "translateY(-8px)" },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "fade-in-up": "fade-in-up 1s ease-out forwards",
        "bounce-slow": "bounce-slow 2.5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}